apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bx4rh4b82-go 
  janus-idp.io/tekton: bx4rh4b82-go
  backstage.io/kubernetes-id: bx4rh4b82-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bx4rh4b82-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml